RGB=imread('rankfiltered.jpg');
[BW,maskedImage] = segmentImage(RGB)
imshowpair(BW,maskedImage,"montage");
function [BW,maskedImage] = segmentImage(RGB)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB) segments image RGB using
%  auto-generated code from the imageSegmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 11-Jun-2022
%----------------------------------------------------


% Convert RGB image into L*a*b* color space.
X = rgb2lab(RGB);

% Graph cut
foregroundInd = [11837 13059 36452 37581 39305 61698 70378 76635 77147 79062 90822 100193 100704 100705 102034 106660 113298 117618 132757 138922 145817 148586 150716 160458 161430 166108 168163 171757 182923 183435 184623 187613 193255 193344 194377 194889 199003 210183 210695 211633 234708 248634 249165 ];
backgroundInd = [4707 4708 16255 19628 65222 100249 105610 106524 120985 126228 156796 159785 168112 169135 199465 199976 202449 225395 ];
L = superpixels(X,1411,'IsInputLab',true);

% Convert L*a*b* range to [0 1]
scaledX = prepLab(X);
BW = lazysnapping(scaledX,L,foregroundInd,backgroundInd);

% Create masked image.
maskedImage = RGB;
maskedImage(repmat(~BW,[1 1 3])) = 0;
end

function out = prepLab(in)

% Convert L*a*b* image to range [0,1]
out = in;
out(:,:,1) = in(:,:,1) / 100;  % L range is [0 100].
out(:,:,2) = (in(:,:,2) + 86.1827) / 184.4170;  % a* range is [-86.1827,98.2343].
out(:,:,3) = (in(:,:,3) + 107.8602) / 202.3382;  % b* range is [-107.8602,94.4780].

end
